### ISSUE TITLE
Friendship request

### ISSUE THREAD

**Issue by je-santos** [LukasMosser/digital_rocks_data#1]
Wanna become friends?
https://github.com/je-santos/MPLBM-UT

**Comment by LukasMosser** [comment]
Hey, of course! ❤️ 

Do you think there is a strong overlap with your repo, or could yours benefit from these functionalities in this library?

**Comment by je-santos** [comment]
Continuing this tread on https://github.com/je-santos/MPLBM-UT/issues/63

**Comment by je-santos** [comment]
We'll code an example on our end using one of the samples.

Another cool thing that we could do together is to have some sort of perm function in your class:

img.perm(dim='z', num_cores=10)

**Comment by LukasMosser** [comment]
I'm guessing `.perm`would in this case compute a permeability?

Ideally I'd like to keep this fairly "load data from web and into xarray" only and have any other functionality separated out. 

I have some ideas e.g. how one could go from what I can do with drd to e.g. building some machine learning datasets programmatically. But even that I would want to have separate because it adds some specific dependencies and assumes some use case.
